- LLCONTROL/afhba-llcontrol-cpucopy.c
modified:   afhba-llcontrol-cpucopy.c
usec counter was being overwritten.
> Changed the location of pollcat and difftime in SPAD.

- HAPI/llc-test-harness-twobox.py
modified:   HAPI/llc-test-harness-twobox.py
> Added a run0 so that we can dynamically recalculate NCHAN.

- scripts/acqproc.sh
- scripts/llc-config-utility.py
acqproc now configures itself to run for any system by looking inside the acq2106.
> Auto config for acqproc.sh.

- scripts/acqproc.sh
- scripts/llc-config-utility.py
Now the script will complain if there is no acq2106 available. It will check that the specific acq2106 asked for is actually connected otherwise it will now error out.
> Added some exception handling into acqproc.sh.

- scripts/latency_on_diff_histo.py
new file:   scripts/latency_on_diff_histo.py
> Added a new latency analysis script.

- scripts/acqproc.sh
- scripts/llc-config-utility.py
Also added microsecond counter and LLC stats to the automated llc-config script.
> Auto config

- scripts/acqproc_multi.sh
> Added a new parallel sync_role command structure.

- scripts/acqproc_multi.sh
> Added better sync_role mode support.

- scripts/acqproc_multi_bolo.sh
new file:   scripts/acqproc_multi_bolo.sh
> Added a new control script for operation with BOLO.

- scripts/acqproc.sh
- scripts/acqproc_multi.sh
- scripts/acqproc_multi_bolo.sh
modified:   scripts/acqproc.sh
modified:   scripts/acqproc_multi_bolo.sh
> Fixed TASKSET typo in acqproc family.

- .gitignore
- FUNCTIONAL_TESTS/hbfarm425.cpp
- FUNCTIONAL_TESTS/multisitecheckramp.cpp
- Makefile
- STREAM/Makefile
- STREAM/RTM_T_Device.cpp
- STREAM/rtm-t-stream-disk.cpp
- STREAM/rtm-t-stream.cpp
- STREAM/rtm-t-stream.h
- STREAM/rtm-t-stream.py
- afhba_stream_drv.c
Hi Peter,
This is my current branch that i use for streaming data via mgt.
librtm-t-stream.so with
1. RtmStreamStart
open and init stream on dev id
2. RtmStreamGetBuffer
copy next buffer to user buffer
3. RtmStreamStop 
request stop, save for multithreading
4. RtmStreamClose    
free resources, called for cleanup
The python example shows how to use it in a user application.
The pr contains minor fixes and convenience updates:
* updated .gitignore
* fixed some compiler warnings
* debug symbols option in Makefile
* fixed poll reset old behaviour for write : TODO: will write never block?
> Final version of how i use the new rtm-t-stream shared lib

- ACQPROC/configs/7_uut_system.json
- ACQPROC/configs/acq2106_423_4x3.json
- ACQPROC/configs/acq2106_423_4x4.json
- ACQPROC/configs/acq424_remote_ao.json
- ACQPROC/configs/east1.json
new file:   acq424_remote_ao.json
> Added new remote ao JSON.

- scripts/llc-run-full-auto-two-076-079
modified:   scripts/llc-run-full-auto-two-076-079
> Separated uut config from capture.

- ACQPROC/AcqSys.cpp
- scripts/acqproc_multi.sh
- scripts/llc-config-utility.py
- scripts/llc-run-full-auto-two-076-079
modified:   scripts/llc-run-full-auto-two-076-079
> Made control script work with 4AOs.

- ACQPROC/AcqSys.cpp
modified:   ACQPROC/AcqSys.cpp
> Removed a redundant comment.

- scripts/acqproc_multi.sh
- scripts/llc-config-utility.py
modified:   scripts/llc-config-utility.py
> Removed redundant code and added PWM support to acqproc scripts.

- scripts/acqproc_multi.sh
- scripts/list_capture_uuts.py
new file:   scripts/list_capture_uuts.py
Removed in favour of an auto-detect from the
configuration file. Also removed redundant PWM
function.
> Removed environment variable switches for capture_uuts.

- scripts/acqproc_multi.sh
> Change ACQPROC_CONFIG to $1 argument.

- HAPI/thomson_analysis.py
modified:   HAPI/thomson_analysis.py
> Removed bad comment from thomson_analysis.py.

- ACQPROC/AcqHw.cpp
> Added +2 samples to buffer in AcqHw.cpp.

- HAPI/thomson_config_clockondemand.py
- scripts/llc-run-full-auto-thomson
modified:   HAPI/thomson_config_clockondemand.py
modified:   scripts/llc-run-full-auto-thomson
> Added in THOMSON ext uclk counter functionality.

- HAPI/thomson_config_sampleondemand.py
- scripts/llc-run-full-auto-thomson
Tested with 16384 to decrease buffer consumption rate.
> Made the thomson buffer length user configurable. Default is 4096.

- scripts/llc-run-full-auto-thomson
modified:   scripts/llc-run-full-auto-thomson
> Added a user controllable demux argument for THOMSON systems.

- ACQPROC/configs/acq2106_4AI_2AO.json
new file:   ACQPROC/configs/acq2106_4AI_2AO.json
> Added new json file.

- scripts/llc-config-utility.py
If the system is not configured the same as specified in the JSON then 
there is a message printed to the console to warn the user.
> New method to verify UUT is configured as specified by JSON config.

- scripts/stream-to-ramdisk-oneshot
sam@humla
modified:   scripts/stream-to-ramdisk-oneshot
Added recycle argument to stream-to-ramdisk-oneshot
> Added recycle argument to stream-to-ramdisk-oneshot

- FUNCTIONAL_TESTS/isramp.cpp
- scripts/stream-to-ramdisk-verify
sam@humla
modified:   FUNCTIONAL_TESTS/isramp.cpp
new file:   scripts/stream-to-ramdisk-verify
> Created stream then verify script and added logging argument

- FUNCTIONAL_TESTS/isramp.cpp
- scripts/stream-to-ramdisk-verify
modified:   scripts/stream-to-ramdisk-verify
modified:   FUNCTIONAL_TESTS/isramp.cpp
sam@humla
> Cleaned up stream verify and fixed isramp bug when writing logfile

- HAPI/hts_multistream.py
new file:   HAPI/hts_multistream.py
> Added hts_multistream.py

- HAPI/afhba_check_links.py
- HAPI/hts_multistream.py
modified:   HAPI/afhba_check_links.py
modified:   HAPI/hts_multistream.py
> multistream now calls afhba_check_links

- HAPI/hts_multistream.py
modified:   HAPI/hts_multistream.py
> Added arg to get mean cpu usage

- scripts/hts_thrasher.sh
new file:   scripts/hts_thrasher.sh
> Added hts thrasher script

- ACQPROC/configs/PLANCK_M_413_S_414_415.json
new file:   ACQPROC/configs/PLANCK_M_413_S_414_415.json
> Added 413,414,415 llc config

- scripts/acqproc_multi.sh
> acqproc now works for other user accounts

- scripts/llc-config-utility.py
modified:   scripts/llc-config-utility.py
> Detects DIO482ELF

- scripts/acqproc_getconfig.py
- scripts/acqproc_multi.sh
- scripts/list_capture_uuts.py
modified:   scripts/acqproc_getconfig.py
modified:   scripts/list_capture_uuts.py
> now handles sync role in json correctly

- HAPI/hts_multistream.py
modified:   HAPI/hts_multistream.py
> Added concat arg

- HAPI/ht_stream.py
> Added ht_stream.py

- FUNCTIONAL_TESTS/isramp.cpp
modified:   FUNCTIONAL_TESTS/isramp.cpp
> Added missing break and removed debug print

- HAPI/hts_multistream.py
modified:   HAPI/hts_multistream.py
> Fixed error with incorrect values passed to isramp when dio is present

- scripts/mount-ramdisk
modified:   scripts/mount-ramdisk
> Stop ramdisk needing sudo to write to
